when:
  - event: [push, manual]

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      partial: false
      recursive: true

steps:
  - name: mirror to Github
    when:
      - event: [ push, manual ]
        branch: [ master, main ]
    depends_on: []
    image: codeberg.org/mathisdt/buildhelper:latest
    pull: true
    environment:
      TOKEN_GITHUB:
        from_secret: TOKEN_GITHUB
    commands: |
      git remote add github https://mathisdt:$TOKEN_GITHUB@github.com/mathisdt/$CI_REPO_NAME.git
      git push github
